In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

iris=load_iris()
x_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=0.25)

#create a gaussian nb classifier
gnb=GaussianNB()

#train the model using training set 
gnb.fit(x_train,y_train)

#predict the response for test data set
y_predict=gnb.predict(x_test)


#import metrics module for accuracy calculation
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test,y_predict))

Accuracy: 0.9473684210526315


In [13]:
#naive bayes
import numpy as np
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score

#load the iris dataset
iris=datasets.load_iris()
X=iris.data
y=iris.target
#split the data into training and testing sets(80% training,20% testing)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#create a Gaussian Naive Bayes classifier
nb_classifier=GaussianNB()

#Train the classifier using the train data
nb_classifier.fit(X_train,y_train)

#make predictions on the testing data
y_pred=nb_classifier.predict(X_test)

#calculate the accuracy of the classifier
accuracy=accuracy_score(y_test,y_pred)
print(accuracy)
print(f"Accuracy: {accuracy*100:.2f}%")

1.0
Accuracy: 100.00%


In [19]:
#naive bayes
import numpy as np
from sklearn import datasets,metrics
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

#load the iris dataset
iris=datasets.load_iris()
X=iris.data
y=iris.target
#split the data into training and testing sets(80% training,20% testing)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#create a Gaussian Naive Bayes classifier
nb_classifier=GaussianNB()

#Train the classifier using the train data
nb_classifier.fit(X_train,y_train)

#make predictions on the testing data
y_pred=nb_classifier.predict(X_test)

#consusion matrix
res=confusion_matrix(y_test,y_pred)
print("confusion_matrix \n",res)

#classification report
res1=classification_report(y_test,y_pred)
print("Classification_report \n",res1)

#calculate the accuracy of the classifier
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:\n",accuracy)
# print(f"Accuracy: {accuracy*100:.2f}%")

confusion_matrix 
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification_report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy:
 1.0


In [12]:
import numpy as np 
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('food.csv')
X = data.iloc[:, :3]
# print(X)
y= data.iloc[:, 3]

le = LabelEncoder()
categorical_columns = ['Ingredient']  
for col in categorical_columns:
    X[col] = le.fit_transform(X[col])
y = le.fit_transform(y)


X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
knn = GaussianNB()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
sample=[[1,10,9]]
k=knn.predict(sample)
print(k)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)


[0]
1.0


In [10]:
import numpy as np 
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder

data = pd.read_csv('food.csv')
X = data.iloc[:, :3]
# print(X)
y= data.iloc[:, 3]

le = LabelEncoder()
categorical_columns = ['Ingredient']  
for col in categorical_columns:
    X[col] = le.fit_transform(X[col])
y = le.fit_transform(y)


X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
knn = GaussianNB()
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)

sample=[[1,10,9]]
k=knn.predict(sample)
print(k)
accuracy = accuracy_score(y_test,y_pred)
print(accuracy)

[0]
1.0
